### ISSUE TITLE
ImageView setImageUri 设置网络图片的url，会报错

### ISSUE THREAD

**Issue by zhaocz2015** [Jude95/ExGridView#1]
你好jude95：
我在使用的过程中，碰到一点问题，希望给予指教。
应用场景：
`添加多张图片后保存，然后再进行编辑，那么展示的应该是之前的多张图片`
看到imageView 提供了setImageUri的方法，看起来可以直接设置网络图片uri
但是在使用过程中报错

```
Unable to decode stream: java.io.FileNotFoundException /http:/xxxx/xxx.png
I/System.out(14749): resolveUri failed on bad bitmap uri: http://xxxx/xxxx.png
```

查看源码，ImagePieceView 封装ImageView使用，但是会报错。
是否可以考虑ImagePieceView 封装使用可以setImageUri直接解析图片url的image组件，比如非死不可的SimpleDraweeView。
期待你的回复，谢谢。

**Comment by Jude95** [comment]
库应该是功能单纯的，这是个控制布局的view不应该负责网络。
每个项目都肯定有自己的网络图片加载方式，fresco，glide，picasso…如果我擅自使用一种，肯定有人不满，网络加载部分冗余了且无法控制。特别fresco，apk直接大直接1m多，其他也是4-600k。就算主app与库都用一个库，也会出现版本不一致，实例不一致等问题。

自建独立简易网络加载方式虽然不会有体积问题但效率不行，也太简陋，出bug就不好了。

将图片加载方式交给用户注入进来，API会复杂，接入麻烦。某些库直接给每个主流网络库提供注入库。

我很多库都是基于这样的考虑，很多其他大型库也都在网络上用上面之一的处理方式。
综上，我也很蛋疼，最后考虑不做，而是交给用户自己去继承实现一个NetPieceView。也许这一点没在readme写清楚。

**Comment by zhaocz2015** [comment]
多谢jude，受教了
